### ISSUE TITLE
Test Case Compatibility and Integration Issues

### ISSUE THREAD

**Issue by mardini2** [Shy2003/-Project-IV-Group3#9]
The test cases for the `Client_PC01_Tests` project are encountering compatibility issues due to the project targeting `.NETCoreApp,Version=v6.0`. This results in errors.

Steps to Reproduce:
Attempt to run the test cases in the `Client_PC01_Tests` project.
Observe the compatibility errors mentioned above.

Possible Solutions:
Update the project `Client_PC01` to target `net6.0-windows` to align with the test project targeting.
Implement mocks or simulated environments for more integrated testing until the compatibility issues are resolved.

**Comment by mardini2** [comment]
Root Cause:
The root of the issue was the mismatch in target frameworks between the main project and the test project. The test project was targeting .NET Core 6.0 without specifying the necessary OS-specific target framework, which led to compatibility issues when running the tests.

Solution:
After thorough investigation thanks to Ethan, and testing various configurations, the issue was resolved by adjusting the project settings in the following way:

Target OS: Windows. This was crucial for ensuring that all OS-specific features required by the project are appropriately supported.
Target Framework: Updated the target framework to .NET 7.0 (net7.0-windows). This change ensures that the project takes advantage of the latest .NET features and improvements while maintaining compatibility with Windows-specific APIs and components necessary for the project.

Recommendation for Future Projects:
To prevent similar issues in future projects, always specify the appropriate target framework and OS from the outset, especially when the project relies on OS-specific features. Additionally, keeping the project updated to the latest .NET version can help leverage the most recent improvements and ensure better compatibility.

**Comment by AEther-Frisko** [comment]
I ran into this same issue and have been trying to fix it, so I have a quick question regarding it. Do I have to entirely remake my solution and copy over the repo to fix this? Or is there a faster way? I haven't been able to locate where to change the target OS outside otherwise, so I'm assuming I just am missing something.

**Comment by AEther-Frisko** [comment]
> I ran into this same issue and have been trying to fix it, so I have a quick question regarding it. Do I have to entirely remake my solution and copy over the repo to fix this? Or is there a faster way? I haven't been able to locate where to change the target OS outside otherwise, so I'm assuming I just am missing something.

Issue was resolved with help from Ali, fortunately it was not a major problem.
